# **The nn module**
The torch nn module in PyTorch is a core library that provides a wide array of classes and functions designed to help developers build neural networks efficiently and effectively. It abstracts the coplexity of creating and training neural networks by offering pre-built layers. Loss functions, activation function, and other utilities, enabling you to focus on desinging and experimenting with model architecture. <br>
## Key components of torch.nn:
1. **Modules (Layers)**
  - **nn.Module:** The base class for all neural network modules. You custom models and layers should subclass this class.
  - **Common Layers:** Includes layers like nn.Linear (fully connected layer), nn.Conv2d (convolutional layer), nn.LSTM (recurrent layer), and many others.

2. **Activation Functions:**
  - Functions like nn.ReLU, nn.Sigmoid and nn.Tanh introduce non-linearities to the model, allowing it to learn complex patterns.

3. **Loss Functions**:
  - Provides loss functions such as nn.CrossEntropyLoss, and nn.NNLoss to quantify the difference between the models's prediction and the actual targets.
4. **Container Modules:**
  - **nn.Sequential:** A sequential container to stack layer in order.

5. **Regularization and Dropout:**
  - Lyers like nn.Dropout and nn.BatchNorm2d help prevent overfitting and improve the module's ability to generalize to new data.

In [1]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
      out = self.linear(x)
      out = self.sigmoid(out)
      return out

In [2]:
# create dataset
features = torch.randn(10, 5)

model = Model(features.shape[1])

# call model for forward pass
# model.forward (features)
model(features)

tensor([[0.5848],
        [0.5825],
        [0.4050],
        [0.5608],
        [0.3212],
        [0.2646],
        [0.2659],
        [0.7454],
        [0.1922],
        [0.3050]], grad_fn=<SigmoidBackward0>)

In [3]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.1380,  0.4300, -0.2179, -0.0587,  0.2280]], requires_grad=True)

In [4]:
model.linear.bias

Parameter containing:
tensor([-0.2223], requires_grad=True)

In [5]:
!pip install torchinfo

In [6]:
from torchinfo import summary
summary(model, input_size = (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# **Neural Network with hidden layer**

In [7]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    x = self.linear1(x)
    x = self.relu(x)
    x = self.linear2(x)
    x = self.sigmoid(x)
    return x

In [8]:
# create dataset
features = torch.randn(10, 5)

model = Model(features.shape[1])

# call model for forward pass
# model.forward (features)
model(features)

tensor([[0.5491],
        [0.4223],
        [0.5263],
        [0.5500],
        [0.5625],
        [0.5562],
        [0.5045],
        [0.6048],
        [0.5659],
        [0.5520]], grad_fn=<SigmoidBackward0>)

In [9]:
# show moswl weights
model.linear1.weight

Parameter containing:
tensor([[-0.2778,  0.4079, -0.0304, -0.1197,  0.1610],
        [ 0.2397,  0.3674, -0.1090,  0.3347, -0.2797],
        [ 0.1508,  0.3583, -0.0575, -0.3675, -0.4208]], requires_grad=True)

In [10]:
model.linear1.bias

Parameter containing:
tensor([ 0.2752, -0.2329,  0.3563], requires_grad=True)

In [11]:
summary(model, input_size = (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# **Sequential container**

In [12]:
# Create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.layers = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, x):
    return self.layers(x)

In [13]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [14]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [15]:
df.drop(columns = ['id', 'Unnamed: 32'],inplace = True)
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

X_train_tensor = torch.from_numpy(X_train).type(torch.float32)
X_test_tensor = torch.from_numpy(X_test).type(torch.float32)

In [16]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    x = self.linear(x)
    x = self.sigmoid(x)
    return x

  def loss_function(self, y_pred, y_true):
  # clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    loss = - (y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred))
    return loss.mean()

In [17]:
learning_rate = 0.01
epochs = 25

In [18]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor)

  # compute loss
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward
  loss.backward()

  # update weights
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.7006667852401733
Epoch: 2, Loss: 0.7003925442695618
Epoch: 3, Loss: 0.7001254558563232
Epoch: 4, Loss: 0.6998651027679443
Epoch: 5, Loss: 0.6996113061904907
Epoch: 6, Loss: 0.6993635892868042
Epoch: 7, Loss: 0.6991219520568848
Epoch: 8, Loss: 0.6988858580589294
Epoch: 9, Loss: 0.6986551284790039
Epoch: 10, Loss: 0.6984297037124634
Epoch: 11, Loss: 0.6982092261314392
Epoch: 12, Loss: 0.6979934573173523
Epoch: 13, Loss: 0.6977822780609131
Epoch: 14, Loss: 0.6975753903388977
Epoch: 15, Loss: 0.6973727345466614
Epoch: 16, Loss: 0.6971741318702698
Epoch: 17, Loss: 0.6969794034957886
Epoch: 18, Loss: 0.6967882513999939
Epoch: 19, Loss: 0.6966007351875305
Epoch: 20, Loss: 0.6964166760444641
Epoch: 21, Loss: 0.6962358355522156
Epoch: 22, Loss: 0.6960581541061401
Epoch: 23, Loss: 0.6958835124969482
Epoch: 24, Loss: 0.6957117915153503
Epoch: 25, Loss: 0.6955430507659912


In [19]:
model.linear.weight

Parameter containing:
tensor([[-0.0752,  0.1465,  0.1179, -0.0922, -0.0415,  0.1840, -0.1281, -0.0842,
         -0.1364, -0.0966,  0.1005,  0.0136,  0.0277,  0.1532,  0.0193, -0.1676,
         -0.1365,  0.0582, -0.0029,  0.0512, -0.0665, -0.1581, -0.1567, -0.0299,
         -0.0057,  0.1346,  0.1769,  0.0996, -0.0252, -0.0843]],
       requires_grad=True)

# **Evaluation**

In [20]:
# model evaluation
with torch.no_grad():
  y_pred = model(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.5283163785934448


# **Improved Code**

In [21]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    x = self.linear(x)
    x = self.sigmoid(x)
    return x


In [22]:
learning_rate = 0.01
epochs = 25

In [23]:
loss_function = nn.BCELoss()

In [27]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor)

  # compute loss
  loss = loss_function(y_pred, y_train_tensor.unsqueeze(1).float())

  # backward
  loss.backward()

  # update weights
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.5185304284095764
Epoch: 2, Loss: 0.5091597437858582
Epoch: 3, Loss: 0.5002110600471497
Epoch: 4, Loss: 0.4916575253009796
Epoch: 5, Loss: 0.4834739565849304
Epoch: 6, Loss: 0.47563743591308594
Epoch: 7, Loss: 0.4681266248226166
Epoch: 8, Loss: 0.460921972990036
Epoch: 9, Loss: 0.45400503277778625
Epoch: 10, Loss: 0.44735920429229736
Epoch: 11, Loss: 0.44096872210502625
Epoch: 12, Loss: 0.43481919169425964
Epoch: 13, Loss: 0.42889705300331116
Epoch: 14, Loss: 0.4231901168823242
Epoch: 15, Loss: 0.41768649220466614
Epoch: 16, Loss: 0.4123755097389221
Epoch: 17, Loss: 0.4072471261024475
Epoch: 18, Loss: 0.4022918939590454
Epoch: 19, Loss: 0.3975011110305786
Epoch: 20, Loss: 0.3928666412830353
Epoch: 21, Loss: 0.38838064670562744
Epoch: 22, Loss: 0.38403618335723877
Epoch: 23, Loss: 0.3798263967037201
Epoch: 24, Loss: 0.37574502825737
Epoch: 25, Loss: 0.37178611755371094


** Reshape and view work same

# **The torch.optim module**
torch.optim is a module in PyTorch that provides a variety of optimization algorithm use to update the parameter of your model during training. <br>

It includes common optimizers like Stochastic Gradient Descent(SGD), Adam, RMSprop, and more. <br>

It handles weight updates efficiently, including additional features like learning rate scheduling and weight decay (regularization). <br>

The model parameters() method in PyTorch referiews an iterator overall the trainable parameter is module. There parameters are intances of torch.nn.parance (weight and biases) in a good model. These parameter arc instances of torch parameter include.
- **weights:** The weight matrices of layers like nn.Linear, nn.Con2d,etc.
- **Biases:** The bias terms of layers (if they exist). <br>
The optimizer uses these parameters to compute gradients and update them during training.

In [33]:
model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor)

  # compute loss
  loss = loss_function(y_pred, y_train_tensor.unsqueeze(1).float())

  # clear gradient
  optimizer.zero_grad()

  # backward
  loss.backward()

  # update weights
  optimizer.step()

  # zero gradients

  print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.9566766023635864
Epoch: 2, Loss: 0.9232178926467896
Epoch: 3, Loss: 0.8914916515350342
Epoch: 4, Loss: 0.8614583611488342
Epoch: 5, Loss: 0.8330714106559753
Epoch: 6, Loss: 0.8062766790390015
Epoch: 7, Loss: 0.7810143232345581
Epoch: 8, Loss: 0.7572193145751953
Epoch: 9, Loss: 0.7348225712776184
Epoch: 10, Loss: 0.7137526273727417
Epoch: 11, Loss: 0.6939358115196228
Epoch: 12, Loss: 0.6752976775169373
Epoch: 13, Loss: 0.6577642560005188
Epoch: 14, Loss: 0.6412627696990967
Epoch: 15, Loss: 0.6257225871086121
Epoch: 16, Loss: 0.6110755205154419
Epoch: 17, Loss: 0.5972573161125183
Epoch: 18, Loss: 0.5842071175575256
Epoch: 19, Loss: 0.5718684196472168
Epoch: 20, Loss: 0.560188353061676
Epoch: 21, Loss: 0.5491185784339905
Epoch: 22, Loss: 0.5386141538619995
Epoch: 23, Loss: 0.5286341309547424
Epoch: 24, Loss: 0.5191409587860107
Epoch: 25, Loss: 0.5101001858711243
