# **Import torch and check version**

In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


# **Check GPU availability**

In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")

else:
  print("GPU is not available. Using CPU...")

GPU is available
Using GPU : Tesla T4


# **Creating a Tensors**

In [4]:
# Using empty -> create space (2,3) and show existence value. Not assign new value
torch.empty(2,3)

tensor([[-3.5596e-28,  4.3897e-41, -3.5596e-28],
        [ 4.3897e-41,  6.4748e-12,  4.3898e-41]])

In [5]:
# check type
a = torch.empty(2,3)
type(a)

torch.Tensor

In [6]:
# Using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.5224, 0.1806, 0.9713],
        [0.1674, 0.3094, 0.9086]])

In [9]:
# use of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [11]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [12]:
# using tensor -> create custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# arange
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [16]:
# using linspace
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [17]:
# using eye
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
# full
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# **Tensor Shapes**

In [19]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
x.shape

torch.Size([2, 3])

# **Same shape new tensor**

In [21]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6068374192602033460, 3544396906907710257, 6499037538516808238]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [24]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

Why error?<br>
Because x is integer type and rand is a float type. That's why showing error.

# **Tensor Data Types**

In [25]:
# find data type
x.dtype

torch.int64

In [26]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [28]:
# using to() -> convert data type
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [29]:
torch.rand_like(x, dtype = torch.float64)

tensor([[0.0526, 0.5262, 0.4768],
        [0.9552, 0.9288, 0.0835]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |

# **Mathematical Operations**
### 1. Scaler operation

In [30]:
x = torch.rand(2,2)
x

tensor([[0.2666, 0.6274],
        [0.2696, 0.4414]])

In [31]:
# addition
x + 2

tensor([[2.2666, 2.6274],
        [2.2696, 2.4414]])

In [32]:
# subtraction
x - 2

tensor([[-1.7334, -1.3726],
        [-1.7304, -1.5586]])

In [33]:
# multiplication
x * 3

tensor([[0.7997, 1.8823],
        [0.8089, 1.3241]])

In [34]:
# division
x / 3

tensor([[0.0889, 0.2091],
        [0.0899, 0.1471]])

In [35]:
# int division
(x * 100)//3

tensor([[ 8., 20.],
        [ 8., 14.]])

In [36]:
# mode
((x * 100)//3)%2

tensor([[0., 0.],
        [0., 0.]])

In [37]:
# power
x **2

tensor([[0.0711, 0.3937],
        [0.0727, 0.1948]])

# **2. Element wise operation**

In [2]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.0294, 0.6162, 0.1545],
        [0.1258, 0.0463, 0.5246]])
tensor([[0.4691, 0.6350, 0.5017],
        [0.2865, 0.8571, 0.9987]])


In [3]:
# add
a + b

tensor([[0.4985, 1.2512, 0.6561],
        [0.4123, 0.9033, 1.5233]])

In [4]:
# sub
a - b

tensor([[-0.4397, -0.0188, -0.3472],
        [-0.1607, -0.8108, -0.4741]])

In [5]:
# multiply
a * b

tensor([[0.0138, 0.3913, 0.0775],
        [0.0360, 0.0397, 0.5239]])

In [6]:
# division
a/b

tensor([[0.0627, 0.9704, 0.3079],
        [0.4390, 0.0540, 0.5253]])

In [7]:
# power
a ** b

tensor([[0.1913, 0.7353, 0.3918],
        [0.5521, 0.0718, 0.5251]])

In [8]:
# mod
a % b

tensor([[0.0294, 0.6162, 0.1545],
        [0.1258, 0.0463, 0.5246]])

In [9]:
# abs
c = torch.tensor([-1,-2,-3])
torch.abs(c)

tensor([1, 2, 3])

In [10]:
# negative
torch.neg(c)

tensor([1, 2, 3])

In [11]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [12]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [13]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [14]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [15]:
# clamp
torch.clamp(d, min =2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# **Reduction Operation**

In [16]:
e = torch.randint(size = (2,3), low=0, high=10)
e

tensor([[6, 4, 4],
        [1, 0, 0]])

In [17]:
# sum
torch.sum(e)

tensor(15)

In [18]:
# sum along column
torch.sum(e, dim=0)

tensor([7, 4, 4])

In [19]:
# sum along rows
torch.sum(e, dim=1)

tensor([14,  1])

In [23]:
# mean
print(torch.mean(e, dtype = torch.float32))
print(torch.mean(e.to(torch.float32), dim=0))
print(torch.mean(e.to(torch.float32), dim=1))

tensor(2.5000)
tensor([3.5000, 2.0000, 2.0000])
tensor([4.6667, 0.3333])


In [24]:
# median
torch.median(e)

tensor(1)

In [25]:
# max and min
torch.max(e)

tensor(6)

In [26]:
torch.min(e)

tensor(0)

In [29]:
# product
torch.prod(e)

tensor(0)

In [31]:
# standar deviation
torch.std(e.to(torch.float32))

tensor(2.5100)

In [32]:
# variance
torch.var(e.to(torch.float32))

tensor(6.3000)

In [33]:
# argmax -> max position
torch.argmax(e)

tensor(0)

In [34]:
# argmin
torch.argmin(e)

tensor(4)

# **Matrix Operation**

In [35]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[4, 0, 1],
        [2, 8, 8]])
tensor([[1, 4],
        [1, 4],
        [7, 0]])


In [36]:
# matrix multiplication
torch.matmul(f,g)

tensor([[11, 16],
        [66, 40]])

In [37]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [38]:
# transpose
torch.transpose(f,0,1)

tensor([[4, 2],
        [0, 8],
        [1, 8]])

In [41]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 0., 4.],
        [5., 8., 4.],
        [6., 9., 9.]])

In [42]:
# deteminant
torch.det(h)

tensor(-12.)

In [43]:
# inverse
torch.inverse(h)

tensor([[-3.0000, -3.0000,  2.6667],
        [ 1.7500,  2.0000, -1.6667],
        [ 0.2500,  0.0000,  0.0000]])

# **Comparison Operations**

In [44]:
i = torch.randint(size=(2,3),low=0, high=10)
j = torch.randint(size=(2,3),low=0, high=10)

print(i)
print(j)

tensor([[6, 0, 6],
        [1, 0, 5]])
tensor([[9, 2, 8],
        [1, 0, 1]])


In [45]:
# greater than
i > j

tensor([[False, False, False],
        [False, False,  True]])

In [46]:
# less than
i < j

tensor([[ True,  True,  True],
        [False, False, False]])

In [48]:
# equal to
i == j

tensor([[False, False, False],
        [ True,  True, False]])

In [49]:
# not equal to
i != j

tensor([[ True,  True,  True],
        [False, False,  True]])

In [50]:
# greater than equal to
i >= j

tensor([[False, False, False],
        [ True,  True,  True]])

In [51]:
# less than equal to
i <= j

tensor([[ True,  True,  True],
        [ True,  True, False]])

# **6. Special Functions**

In [52]:
k = torch.randint(size=(2,3), low=0, high=10)
k

tensor([[3, 7, 3],
        [9, 9, 5]])

In [53]:
# log
torch.log(k.to(torch.float32))

tensor([[1.0986, 1.9459, 1.0986],
        [2.1972, 2.1972, 1.6094]])

In [54]:
# exp
torch.exp(k.to(torch.float32))

tensor([[  20.0855, 1096.6332,   20.0855],
        [8103.0840, 8103.0840,  148.4132]])

In [55]:
# sqrt
torch.sqrt(k.to(torch.float32))

tensor([[1.7321, 2.6458, 1.7321],
        [3.0000, 3.0000, 2.2361]])

In [56]:
# sigmoid
torch.sigmoid(k.to(torch.float32))

tensor([[0.9526, 0.9991, 0.9526],
        [0.9999, 0.9999, 0.9933]])

In [57]:
# softmax
torch.softmax(k.to(torch.float32), dim=0)

tensor([[0.0025, 0.1192, 0.1192],
        [0.9975, 0.8808, 0.8808]])

In [58]:
# relu
torch.relu(k.to(torch.float32))

tensor([[3., 7., 3.],
        [9., 9., 5.]])

# **Inplace Operations**

In [59]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6727, 0.4216, 0.6892],
        [0.0406, 0.2993, 0.6697]])
tensor([[0.9452, 0.3267, 0.7141],
        [0.9819, 0.4579, 0.3105]])


In [60]:
m + n
# result will store in new memory. But when we are dealing with large dataset then it occupy large memory.

tensor([[1.6179, 0.7482, 1.4033],
        [1.0224, 0.7573, 0.9802]])

In [61]:
# add m , n and store in m
m.add_(n)

tensor([[1.6179, 0.7482, 1.4033],
        [1.0224, 0.7573, 0.9802]])

In [62]:
m

tensor([[1.6179, 0.7482, 1.4033],
        [1.0224, 0.7573, 0.9802]])

In [65]:
torch.relu(n)
# store in new memory

tensor([[0.9452, 0.3267, 0.7141],
        [0.9819, 0.4579, 0.3105]])

In [66]:
n.relu_()

tensor([[0.9452, 0.3267, 0.7141],
        [0.9819, 0.4579, 0.3105]])

# **Copying a Tensor**

In [67]:
a  = torch.rand(2,3)
a

tensor([[0.9774, 0.8429, 0.8493],
        [0.7128, 0.6738, 0.6750]])

In [68]:
b = a

In [69]:
b

tensor([[0.9774, 0.8429, 0.8493],
        [0.7128, 0.6738, 0.6750]])

In [70]:
a[0][0] = 0

In [71]:
a

tensor([[0.0000, 0.8429, 0.8493],
        [0.7128, 0.6738, 0.6750]])

In [72]:
b

tensor([[0.0000, 0.8429, 0.8493],
        [0.7128, 0.6738, 0.6750]])

In [73]:
id(a)

137526472791344

In [74]:
id(b)

137526472791344

In [75]:
b = a.clone()

In [76]:
a

tensor([[0.0000, 0.8429, 0.8493],
        [0.7128, 0.6738, 0.6750]])

In [77]:
b

tensor([[0.0000, 0.8429, 0.8493],
        [0.7128, 0.6738, 0.6750]])

In [78]:
a[0][0]=10

In [79]:
a

tensor([[10.0000,  0.8429,  0.8493],
        [ 0.7128,  0.6738,  0.6750]])

In [80]:
b

tensor([[0.0000, 0.8429, 0.8493],
        [0.7128, 0.6738, 0.6750]])

In [81]:
id(a)

137526472791344

In [82]:
id(b)

137526473014736

# **Tensor Operations on GPU**

In [83]:
torch.cuda.is_available()

True

In [84]:
device = torch.device('cuda')

In [85]:
# creating a new tensor on GPU
torch.rand(2,3).to(device)

tensor([[0.0676, 0.0016, 0.8946],
        [0.7392, 0.1856, 0.7962]], device='cuda:0')

In [87]:
# moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.7762, 0.9772, 0.8626],
        [0.1465, 0.1791, 0.4121]])

In [89]:
b = a.to(device)

In [90]:
b

tensor([[0.7762, 0.9772, 0.8626],
        [0.1465, 0.1791, 0.4121]], device='cuda:0')

In [91]:
b + 5

tensor([[5.7762, 5.9772, 5.8626],
        [5.1465, 5.1791, 5.4121]], device='cuda:0')

In [92]:
import time

# Define the size of the matrices
size = 10000  #Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# Create corresponding matrices on GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# Measure time CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) #Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time: 4f}")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# Measure time GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) #Matrix multiplication on CPU
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time: 4f}")

# compare results
print("\nSpeed up (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU:  16.573394
Time on GPU:  0.104504

Speed up (CPU time / GPU time): 158.59047323549072


# **Reshaping Tensors**

In [93]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [94]:
# reshaps
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [95]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [96]:
b = torch.rand(2,3,4)

In [97]:
b

tensor([[[0.2825, 0.6376, 0.1701, 0.9188],
         [0.5254, 0.5022, 0.2263, 0.8603],
         [0.6697, 0.0353, 0.7765, 0.6331]],

        [[0.2647, 0.2308, 0.5850, 0.5445],
         [0.7991, 0.3188, 0.3943, 0.7276],
         [0.6745, 0.0967, 0.5054, 0.0395]]])

In [98]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [99]:
# unsqueeze
c = torch.rand(256, 256, 3)
c.unsqueeze(0).shape

torch.Size([1, 256, 256, 3])

In [100]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# **NumPy and PyTorch**

In [101]:
import numpy as np

In [102]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [104]:
b = a.numpy()
b

array([1, 2, 3])

In [105]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [106]:
torch.from_numpy(c)

tensor([1, 2, 3])