# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)
x, x.shape

(tensor([[0.9753, 0.6533, 0.1269, 0.8329, 0.9851, 0.3260, 0.2972],
         [0.3076, 0.5409, 0.7621, 0.5974, 0.0792, 0.5445, 0.0221],
         [0.2332, 0.3144, 0.9360, 0.3597, 0.5123, 0.7526, 0.7078],
         [0.1363, 0.4049, 0.5494, 0.7108, 0.3552, 0.8819, 0.4258],
         [0.2442, 0.8176, 0.0796, 0.5179, 0.3671, 0.4511, 0.5918],
         [0.6458, 0.4725, 0.9443, 0.2765, 0.2396, 0.9529, 0.6029],
         [0.2248, 0.9638, 0.8868, 0.2450, 0.9642, 0.8170, 0.5380]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
y = tensor = torch.rand(1,7)
# Perform matrix multiplication
z = torch.matmul(x, y.T)
z, z.shape

(tensor([[3.1388],
         [2.1694],
         [2.2756],
         [1.5558],
         [2.4473],
         [1.1782],
         [2.0329]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(7,7)
Y = torch.rand(1,7)

# Matrix multiply tensors
z = torch.matmul(X, Y.T)
z, z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [3]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [2]:
# Set random seed
import torch
torch.manual_seed(1234)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
# Create two random tensors on GPU
x = torch.rand(2,3).to(device)
y = torch.rand(2,3).to(device)
x, y

cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [4]:
# Perform matmul on tensor_A and tensor_B
z = torch.matmul(x, y.T).to(device)
z, z.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [5]:
# Find max
print(f"max : {torch.max(z)}")
# Find min
print(f"min : {torch.min(z)}")

max : 0.5617256760597229
min : 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [6]:
# Find arg max
print(f"arg max :{torch.argmax(z)}")

# Find arg min
print(f"arg min : {torch.argmin(z)}")

arg max :3
arg min : 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [7]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(size = (1, 1, 1, 10))

# Remove single dimensions
tensor_r = torch.squeeze(tensor)

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensor_r, tensor_r.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
